// <auto-generated />
namespace asp_example.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddDisplayOrderToTodo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDisplayOrderToTodo));
        
        string IMigrationMetadata.Id
        {
            get { return "201401261633137_AddDisplayOrderToTodo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
